version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bookhub-postgres
    environment:
      POSTGRES_DB: bookhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookhub-network

  mongodb:
    image: mongo:7.0
    container_name: bookhub-mongodb
    environment:
      MONGO_INITDB_DATABASE: bookhub
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bookhub-network

  redis:
    image: redis:7.2-alpine
    container_name: bookhub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bookhub-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  bookhub-network:
    driver: bridge