spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bookhub
    username: postgres
    password: postgres

  data:
    mongodb:
      uri: mongodb://mongodb:27017/bookhub
    redis:
      host: redis
      port: 6379

logging:
  level:
    com.hamming.bookhub: INFO